seed: 1
project_name: "Mlp-Mixer"
criterion: "ce"
precision: 16
dry_run: False
lr: .001
min-lr: .001
weight_decay: .00005
batch_size: 128
log_2_sep_rank: 10
eval_batch_size: 128
model_name: "Mlp-Mixer"
depth: 15
width: 250
img_size: 32
patch_size: 4
max_epochs: 41
beta1: 0.9
beta2: 0.999
dataset: "c100"
num-classes: 100
model-name: "vit"
patch: 4
off_benchmark: True
warmup_epoch: 0
autoaugment: True
label-smoothing: True
smoothing: 0.1
rcpaste: True
cutmix: True
mixup: True
dropout: 0.0
heads: 1
num-layers: 7
hidden: 384
mlp-hidden: 384